e_commerce/config/urls.py
from config import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/main/urls.py
from django.urls import path
from .views import IndexView, AboutView

app_name ='main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),

]

e_commerce/users/urls.py
from django.urls import path
from .views import LoginView, RegistrationView, ProfileView, LogoutView
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('cart/', views.users_cart, name='users_cart'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

e_commerce/main/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

class MyForm(forms.Form):
    my_date_field = forms.DateField(widget=AdminDateWidget)

e_commerce/main/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['content'] = "Harmony Home Furnishings"
        return context

class AboutView(TemplateView):
    template_name = 'main/about.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

e_commerce/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">

{% endblock %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center mt-5 pt-5">
       <div class="mt-5 pt-5 bg-white custom-shadow rounded text-center p-4">
        <p>Hello! My name is <strong>Ievgen Kviatkivskyi</strong> and I am an aspiring web developer.</p>
        <p>I created this project for educational purposes to improve my skills in the Django framework,</p>
        <p> as well as in frontend development, specifically in using Bootstrap for layout.</p>
        <p>If you like my pet project, you can contact me via <a href="https://www.linkedin.com/in/ievgen-kviatkivskyi/" target="_blank">LinkedIn</a></p>
        <p>and I can create a similar online store for you, customized to suit your business.</p>
       </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; </p>
        </div>
    </footer>
{% endblock%}


<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="index.html">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="users/login.html">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="deps/icons/grid-fill.svg" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        <li><a class="dropdown-item text-white" href="/catalog/">Все товары</a></li>
                        <li><a class="dropdown-item text-white" href="">Кухня</a></li>
                        <li><a class="dropdown-item text-white" href="goods/catalog.html">Спальня</a></li>
                        <li><a class="dropdown-item text-white" href="goods/catalog.html">Гостинная</a></li>
                        <li><a class="dropdown-item text-white" href="goods/catalog.html">Офис</a></li>
                        <li><a class="dropdown-item text-white" href="goods/catalog.html">Фурнитура</a></li>
                        <li><a class="dropdown-item text-white" href="goods/catalog.html">Декор</a></li>
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="deps/icons/basket2-fill.svg" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="deps/icons/trash3-fill.svg"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    
                </div>
            </div>
        </div>
    </section>
    
    <script src="deps/js/jquery/jquery-3.7.0.min.js"></script>
    <script src="deps/js/jquery-events.js"></script>
    <script src="deps/js/jquery-ajax.js"></script>
    <script src="deps/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>

</html>

e_commerce/templates/main/base.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
   <!-- Style for the footer on the homepage -->
    {% block css %}
    
    {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                                Info
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Delivery and Payment</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Contacts</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">About Us</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="/user/cart/">Cart</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:login' %}">Sign in</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    My Profile
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="/user/cart/">Cart</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:profile' %}">My Account</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="/admin/">Admin panel</a></li>
                                     {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" method="get" action="/catalog/search/" >
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Catalog and shopping cart with fixed positioning on the page -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Catalog -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Online Catalog
                        <img class="mx-1" src="{% static 'deps/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="/catalog/{{category.slug}}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Cart icon, triggers the modal window -->
                {% block modal_cart %} {% endblock%}
               <!-- The markup of the modal window is finished -->
            </div>
        </div>
        <!-- Content -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                   <!-- Empty block at your discretion -->
                  
                </div>
                <div class="col-lg-10">
                    <!-- Content on the page -->
                    {% include 'includes/notifications.html' %}
                    {% block content %}
                    
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    
    {% endblock footer %}
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/jquery-events.js' %}"></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

e_commerce/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">

{% endblock %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
    <h1 class="mt-5 pt-5" style=""><strong>{{ content }}</strong></h1>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy;</p>
        </div>
        
    </footer>
{% endblock%}