e_commerce/config/urls.py
from config import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/goods/urls.py
from django.urls import path
from .views import  CatalogView, ProductView

app_name ='goods'

urlpatterns = [
    path('search/', CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', CatalogView.as_view(), name='index'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
]

e_commerce/main/urls.py
from django.urls import path
from .views import IndexView, AboutView

app_name ='main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),

]

e_commerce/users/urls.py
from django.urls import path
from .views import LoginView, RegistrationView, ProfileView, LogoutView
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('cart/', views.users_cart, name='users_cart'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

e_commerce/orders/models.py
from django.db import models
from goods.models import Product

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="User",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Order creation date")
    phone_number = models.CharField(max_length=20, verbose_name="Phone number")
    requires_delivery = models.BooleanField(default=False, verbose_name="Delivery required")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Delivery address")
    payment_on_get = models.BooleanField(default=False, verbose_name="Cash on delivery")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(max_length=50, default='Processing', verbose_name="Order status")

    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        ordering = ("id",)

    def __str__(self):
        return f"Order № {self.pk} | Customer {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(to=Product, on_delete=models.SET_DEFAULT, null=True, verbose_name="Product",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Quantity")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date of sale")

    class Meta:
        db_table = "order_item"
        verbose_name = "Sold product"
        verbose_name_plural = "Sold products"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

e_commerce/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Avatar')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

e_commerce/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

e_commerce/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse
from users.forms import UserRegistrationForm, ProfileForm
from django.contrib import auth
from django.contrib.auth import login
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from carts.models import Cart
from orders.models import Order, OrderItem
from django.db.models import Prefetch



class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        session_key = self.request.session.session_key
        if user:
            login(self.request, user)
            if session_key:
                forgot_carts = Cart.objects.filter(user=user)
                if forgot_carts.exists():
                    forgot_carts.delete()
            Cart.objects.filter(session_key=session_key).update(user=user)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home - Authorization'
        return context


class RegistrationView(View):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm

    def get(self, request):
        form = self.form_class()
        return self.render_form(request, form)

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            session_key = request.session.session_key
            auth.login(request, user)
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            return HttpResponseRedirect(reverse('main:index'))
        return self.render_form(request, form)

    def render_form(self, request, form):
        context = {
            'title': 'Home - Registration',
            'form': form
        }
        return render(request, self.template_name, context)


class ProfileView(LoginRequiredMixin, UpdateView):
    form_class = ProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('user:profile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home - My Profile'
        orders = Order.objects.filter(user=self.request.user).prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        ).order_by("-id")
        context['orders'] = orders
        return context


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        auth.logout(request)
        return redirect(reverse_lazy('main:index'))


def users_cart(request):
    return render(request, 'users/users_cart.html')

e_commerce/templates/users/login.html
{% extends "main/base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}

<div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Authorization</h2>
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" name="username" id="username" placeholder="enter the username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" name="password" id="password" placeholder="enter the password" required>
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Sign in</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Forgot password?</a> | <a href="{% url 'users:registration' %}">Create account</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p> Or sign in with:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock  %}

e_commerce/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}

 <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Profile</h3>
                        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                            alt="userpic" class="img-fluid rounded-circle"
                                            style="max-width: 150px;">
                                    {% else %}
                                         <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                        alt="" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                    {% endif %}
                                    <input type="file" class="form-control mt-3" id="id_image"
                                        accept="image/*" name="image">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Name*</label>
                                    <input type="text" class="form-control" id="id_first_name"
                                           value="{{ form.first_name.value }}"
                                           placeholder="Enter your name" required name="first_name">
                                           {% if form.first_name.errors %}
                                           <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                           {% endif %}

                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Last Name*</label>
                                    <input type="text" class="form-control" id="id_last_name"
                                        value="{{ form.last_name.value }}"
                                        placeholder="Enter your last name" name="last_name" required>
                                        {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Username*</label>
                                    <input type="text" class="form-control" id="id_username"
                                         value="{{ form.username.value }}"
                                         placeholder="Enter your username" name="username" required>
                                         {% if form.username.errors %}
                                         <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                         {% endif %}

                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email"
                                           value="{{ form.email.value }}"
                                           placeholder="Enter your email *youremail@example.com"
                                           required name="email">
                                           {% if form.email.errors %}
                                           <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                           {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Save</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                {% user_carts request as carts %}
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Cart</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                             {% include 'carts/includes/included_cart.html' %}
                            <!-- Закончилась разметка корзины -->
                        </div>

                    </div>
                </div>
                <!-- Оформленные заказы -->
                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">My orders</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% for order in orders %}
                                <div class="accordion-item">
                                     <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Order № {{ order.id }} - {{ order.created_timestamp }} |  Status: <strong class="mx-2">{{order.status}}</strong>

                                    </button>
                                </h2>
                                 <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                   <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Product</th>
                                                    <th>Quantity</th>
                                                    <th>Price</th>
                                                    <th>Total amount</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.products_price }}</td>

                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                 </div>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                        <!-- Закончилась разметка заказов -->
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock  %}

e_commerce/templates/users/registration.html
{% extends "main/base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Registration</h2>
                    <form action="{% url 'user:registration' %}" method="post" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Name*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                       placeholder="Enter your name" required name="first_name">
                                       {% if form.first_name.errors %}
                                       <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                       {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Last name*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                       placeholder="Enter your last name" required name="last_name">
                                       {% if form.last_name.errors %}
                                       <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                       {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Username*</label>
                                <input type="text" class="form-control" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                    placeholder="Enter your username" required name="username" >
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}

                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                    placeholder="Enter your email" required name="email">
                                     {% if form.email.errors %}
                                     <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                     {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Password*</label>
                                <input type="password" class="form-control" id="id_password1"
                                       value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                       placeholder="Enter the password" required name="password1" >
                                       {% if form.password1.errors %}
                                       <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                       {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Confirm password*</label>
                                <input type="password" class="form-control" id="id_password2"
                                       value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                       placeholder="Confirm password" required name="password2" >
                                       {% if form.password2.errors %}
                                       <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                       {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock  %}

e_commerce/templates/users/users_cart.html
{% extends "main/base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
{% user_carts request as carts %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Cart</h3>
                <div class="container" id="cart-items-container">
                    {% include 'carts/includes/included_cart.html' %}
                </div>
<!--                {% if carts and not order %}-->
<!--                <a class="btn btn-dark" href="orders/create_order.html">-->
<!--                    Checkout-->
<!--                </a>-->
<!--                {% endif %}-->
            </div>
        </div>
    </div>
</div>
{% endblock  %}